abstract final class PerformancePermissions {
  /// Means "may see **other people's** reviews".
  ///
  /// Not a gate on the module as a whole: `guardOwnReviewAccess` lets any
  /// employee read their own regardless, and the service says why in a comment
  /// — a flat permission check there would have locked people out of their own
  /// appraisal. So the app gates the team list on this and never the personal
  /// one.
  static const view = 'PERFORMANCE_VIEW';

  /// Editing, advancing a stage, and finalising.
  static const update = 'PERFORMANCE_UPDATE';

  /// Opening a new review. A separate code from [update].
  static const create = 'PERFORMANCE_CREATE';
}

/// The stages a review moves through, in order.
abstract final class PerformanceStage {
  static const selfAssessment = 'SELF_ASSESSMENT';
  static const managerReview = 'MANAGER_REVIEW';
  static const hrApproval = 'HR_APPROVAL';
  static const finalApproval = 'FINAL_APPROVAL';
  static const completed = 'COMPLETED';

  static const ordered = [
    selfAssessment,
    managerReview,
    hrApproval,
    finalApproval,
    completed,
  ];

  static const labels = {
    selfAssessment: 'Self assessment',
    managerReview: 'Manager review',
    hrApproval: 'HR approval',
    finalApproval: 'Final approval',
    completed: 'Completed',
  };
}

/// One scored dimension of a review.
class ReviewScore {
  const ReviewScore(this.label, this.value);

  final String label;
  final int? value;
}

class PerformanceReview {
  const PerformanceReview({
    required this.id,
    required this.stage,
    required this.finalised,
    this.employeeId,
    this.employeeName,
    this.reviewedByName,
    this.reviewPeriodStart,
    this.reviewPeriodEnd,
    this.overallScore,
    this.scoreWorkQuality,
    this.scoreProductivity,
    this.scoreCommunication,
    this.scoreTeamwork,
    this.scoreInitiative,
    this.scorePunctuality,
    this.scoreLeadership,
    this.scoreProblemSolving,
    this.scoreInnovation,
    this.strengths,
    this.areasForImprovement,
    this.goalsForNextPeriod,
    this.comments,
    this.performanceLevel,
    this.promotionRecommendation,
    this.promotionReadiness,
    this.trainingRecommendation,
    this.recognition,
    this.goalCompletionPercent,
    this.aiSummary,
    this.createdAt,
  });

  final int id;
  final String stage;
  final bool finalised;
  final int? employeeId;
  final String? employeeName;
  final String? reviewedByName;
  final String? reviewPeriodStart;
  final String? reviewPeriodEnd;
  final double? overallScore;

  final int? scoreWorkQuality;
  final int? scoreProductivity;
  final int? scoreCommunication;
  final int? scoreTeamwork;
  final int? scoreInitiative;
  final int? scorePunctuality;
  final int? scoreLeadership;
  final int? scoreProblemSolving;
  final int? scoreInnovation;

  final String? strengths;
  final String? areasForImprovement;
  final String? goalsForNextPeriod;
  final String? comments;
  final String? performanceLevel;
  final String? promotionRecommendation;
  final String? promotionReadiness;
  final String? trainingRecommendation;
  final String? recognition;
  final int? goalCompletionPercent;

  /// Generated by the AI module. Labelled as such wherever it is shown — a
  /// machine's summary of somebody's year should never be mistaken for their
  /// manager's words.
  final String? aiSummary;

  final String? createdAt;

  String get personLabel => employeeName?.trim().isNotEmpty == true
      ? employeeName!.trim()
      : 'Employee #${employeeId ?? id}';

  String get stageLabel =>
      PerformanceStage.labels[stage] ?? stage.replaceAll('_', ' ');

  int get stageIndex {
    final i = PerformanceStage.ordered.indexOf(stage);
    return i < 0 ? 0 : i;
  }

  bool get isComplete => stage == PerformanceStage.completed;

  /// A finalised review is a signed record. Nothing can move it on, and the
  /// screen must not offer to.
  bool get canAdvance => !finalised && !isComplete;

  /// Only a review that has reached the end can be signed off.
  bool get canFinalise => !finalised && isComplete;

  String? get period {
    final start = reviewPeriodStart;
    final end = reviewPeriodEnd;
    if (start == null && end == null) return null;
    return '${start ?? '?'} → ${end ?? '?'}';
  }

  /// The nine scored dimensions, in the order the form asks for them. Every
  /// one is optional, so the detail screen shows only those that were filled.
  List<ReviewScore> get scores => [
        ReviewScore('Work quality', scoreWorkQuality),
        ReviewScore('Productivity', scoreProductivity),
        ReviewScore('Communication', scoreCommunication),
        ReviewScore('Teamwork', scoreTeamwork),
        ReviewScore('Initiative', scoreInitiative),
        ReviewScore('Punctuality', scorePunctuality),
        ReviewScore('Leadership', scoreLeadership),
        ReviewScore('Problem solving', scoreProblemSolving),
        ReviewScore('Innovation', scoreInnovation),
      ];

  List<ReviewScore> get filledScores =>
      scores.where((s) => s.value != null).toList(growable: false);

  bool get hasScores => filledScores.isNotEmpty;

  /// The written half. Empty strings are treated as absent so a blank section
  /// never renders as a heading with nothing under it.
  List<({String title, String body})> get narrative {
    final sections = <({String title, String? body})>[
      (title: 'Strengths', body: strengths),
      (title: 'Areas to improve', body: areasForImprovement),
      (title: 'Goals for next period', body: goalsForNextPeriod),
      (title: 'Training suggested', body: trainingRecommendation),
      (title: 'Recognition', body: recognition),
      (title: 'Comments', body: comments),
    ];
    return [
      for (final s in sections)
        if (s.body?.trim().isNotEmpty == true)
          (title: s.title, body: s.body!.trim()),
    ];
  }

  factory PerformanceReview.fromJson(Map<String, dynamic> json) =>
      PerformanceReview(
        id: (json['id'] as num?)?.toInt() ?? 0,
        stage: json['stage'] as String? ?? PerformanceStage.selfAssessment,
        finalised: json['finalised'] as bool? ?? false,
        employeeId: (json['employeeId'] as num?)?.toInt(),
        employeeName: json['employeeName'] as String?,
        reviewedByName: json['reviewedByName'] as String?,
        reviewPeriodStart: json['reviewPeriodStart'] as String?,
        reviewPeriodEnd: json['reviewPeriodEnd'] as String?,
        overallScore: (json['overallScore'] as num?)?.toDouble(),
        scoreWorkQuality: (json['scoreWorkQuality'] as num?)?.toInt(),
        scoreProductivity: (json['scoreProductivity'] as num?)?.toInt(),
        scoreCommunication: (json['scoreCommunication'] as num?)?.toInt(),
        scoreTeamwork: (json['scoreTeamwork'] as num?)?.toInt(),
        scoreInitiative: (json['scoreInitiative'] as num?)?.toInt(),
        scorePunctuality: (json['scorePunctuality'] as num?)?.toInt(),
        scoreLeadership: (json['scoreLeadership'] as num?)?.toInt(),
        scoreProblemSolving: (json['scoreProblemSolving'] as num?)?.toInt(),
        scoreInnovation: (json['scoreInnovation'] as num?)?.toInt(),
        strengths: json['strengths'] as String?,
        areasForImprovement: json['areasForImprovement'] as String?,
        goalsForNextPeriod: json['goalsForNextPeriod'] as String?,
        comments: json['comments'] as String?,
        performanceLevel: json['performanceLevel'] as String?,
        promotionRecommendation: json['promotionRecommendation'] as String?,
        promotionReadiness: json['promotionReadiness'] as String?,
        trainingRecommendation: json['trainingRecommendation'] as String?,
        recognition: json['recognition'] as String?,
        goalCompletionPercent:
            (json['goalCompletionPercent'] as num?)?.toInt(),
        aiSummary: json['aiSummary'] as String?,
        createdAt: json['createdAt'] as String?,
      );
}

/// The nine competencies a review scores, in the order the form asks for them.
///
/// Each is 1–10 on the DTO. The annotations are never actually enforced —
/// neither the create nor the update endpoint carries `@Valid` — so the range
/// is the form's job, not the server's.
const reviewCompetencies = <({String key, String label})>[
  (key: 'scoreWorkQuality', label: 'Quality of work'),
  (key: 'scoreProductivity', label: 'Productivity'),
  (key: 'scoreCommunication', label: 'Communication'),
  (key: 'scoreTeamwork', label: 'Teamwork'),
  (key: 'scoreInitiative', label: 'Initiative'),
  (key: 'scorePunctuality', label: 'Punctuality'),
  (key: 'scoreLeadership', label: 'Leadership'),
  (key: 'scoreProblemSolving', label: 'Problem solving'),
  (key: 'scoreInnovation', label: 'Innovation'),
];

/// POST /hr/performance and PATCH /hr/performance/{id}
///
/// One class for both, because the backend uses one DTO for both.
///
/// The update path is a **true sparse patch** — every field is null-checked
/// before it is assigned, with no unguarded exceptions — so an omitted key
/// genuinely means "leave it alone". That is unusual in this codebase and
/// worth stating, because the neighbouring candidate and opportunity endpoints
/// behave the opposite way.
///
/// `employeeId` and the review period are only meaningful on create; the
/// update path ignores all three, so the edit form does not offer them.
///
/// `overallScore` is never sent: the service averages whichever competencies
/// are present, skipping nulls, and recomputes it on every write.
///
/// Deliberately absent: `goals`, which the DTO takes as a JSON array string
/// for the goal-tracking bars. Composing JSON by hand is not a phone task, and
/// omitting it leaves whatever the web app set.
class PerformanceReviewRequest {
  const PerformanceReviewRequest({
    this.employeeId,
    this.reviewPeriodStart,
    this.reviewPeriodEnd,
    this.scores = const {},
    this.strengths,
    this.areasForImprovement,
    this.goalsForNextPeriod,
    this.comments,
    this.performanceLevel,
    this.promotionRecommendation,
    this.trainingRecommendation,
    this.recognition,
    this.goalCompletionPercent,
  });

  final int? employeeId;
  final String? reviewPeriodStart;
  final String? reviewPeriodEnd;

  /// Keyed by the DTO's own field names — see [reviewCompetencies].
  final Map<String, int?> scores;

  final String? strengths;
  final String? areasForImprovement;
  final String? goalsForNextPeriod;
  final String? comments;
  final String? performanceLevel;
  final String? promotionRecommendation;
  final String? trainingRecommendation;
  final String? recognition;
  final int? goalCompletionPercent;

  factory PerformanceReviewRequest.from(PerformanceReview review) =>
      PerformanceReviewRequest(
        scores: {
          'scoreWorkQuality': review.scoreWorkQuality,
          'scoreProductivity': review.scoreProductivity,
          'scoreCommunication': review.scoreCommunication,
          'scoreTeamwork': review.scoreTeamwork,
          'scoreInitiative': review.scoreInitiative,
          'scorePunctuality': review.scorePunctuality,
          'scoreLeadership': review.scoreLeadership,
          'scoreProblemSolving': review.scoreProblemSolving,
          'scoreInnovation': review.scoreInnovation,
        },
        strengths: review.strengths,
        areasForImprovement: review.areasForImprovement,
        goalsForNextPeriod: review.goalsForNextPeriod,
        comments: review.comments,
        performanceLevel: review.performanceLevel,
        promotionRecommendation: review.promotionRecommendation,
        trainingRecommendation: review.trainingRecommendation,
        recognition: review.recognition,
        goalCompletionPercent: review.goalCompletionPercent,
      );

  Map<String, dynamic> toJson() {
    String? clean(String? value) {
      final trimmed = value?.trim();
      return (trimmed == null || trimmed.isEmpty) ? null : trimmed;
    }

    return {
      if (employeeId != null) 'employeeId': employeeId,
      if (reviewPeriodStart != null) 'reviewPeriodStart': reviewPeriodStart,
      if (reviewPeriodEnd != null) 'reviewPeriodEnd': reviewPeriodEnd,
      // An unscored competency is left out rather than sent as null, so on an
      // edit it keeps whatever it already had instead of being cleared.
      for (final entry in scores.entries)
        if (entry.value != null) entry.key: entry.value,
      if (clean(strengths) != null) 'strengths': clean(strengths),
      if (clean(areasForImprovement) != null)
        'areasForImprovement': clean(areasForImprovement),
      if (clean(goalsForNextPeriod) != null)
        'goalsForNextPeriod': clean(goalsForNextPeriod),
      if (clean(comments) != null) 'comments': clean(comments),
      if (clean(performanceLevel) != null)
        'performanceLevel': clean(performanceLevel),
      if (clean(promotionRecommendation) != null)
        'promotionRecommendation': clean(promotionRecommendation),
      if (clean(trainingRecommendation) != null)
        'trainingRecommendation': clean(trainingRecommendation),
      if (clean(recognition) != null) 'recognition': clean(recognition),
      if (goalCompletionPercent != null)
        'goalCompletionPercent': goalCompletionPercent,
    };
  }
}
