abstract final class PerformancePermissions {
  /// Means "may see **other people's** reviews".
  ///
  /// Not a gate on the module as a whole: `guardOwnReviewAccess` lets any
  /// employee read their own regardless, and the service says why in a comment
  /// — a flat permission check there would have locked people out of their own
  /// appraisal. So the app gates the team list on this and never the personal
  /// one.
  static const view = 'PERFORMANCE_VIEW';

  /// Editing, advancing a stage, and finalising.
  static const update = 'PERFORMANCE_UPDATE';

  /// Opening a new review. A separate code from [update].
  static const create = 'PERFORMANCE_CREATE';
}

/// The stages a review moves through, in order.
abstract final class PerformanceStage {
  static const selfAssessment = 'SELF_ASSESSMENT';
  static const managerReview = 'MANAGER_REVIEW';
  static const hrApproval = 'HR_APPROVAL';
  static const finalApproval = 'FINAL_APPROVAL';
  static const completed = 'COMPLETED';

  static const ordered = [
    selfAssessment,
    managerReview,
    hrApproval,
    finalApproval,
    completed,
  ];

  static const labels = {
    selfAssessment: 'Self assessment',
    managerReview: 'Manager review',
    hrApproval: 'HR approval',
    finalApproval: 'Final approval',
    completed: 'Completed',
  };
}

/// One scored dimension of a review.
class ReviewScore {
  const ReviewScore(this.label, this.value);

  final String label;
  final int? value;
}

class PerformanceReview {
  const PerformanceReview({
    required this.id,
    required this.stage,
    required this.finalised,
    this.employeeId,
    this.employeeName,
    this.reviewedByName,
    this.reviewPeriodStart,
    this.reviewPeriodEnd,
    this.overallScore,
    this.scoreWorkQuality,
    this.scoreProductivity,
    this.scoreCommunication,
    this.scoreTeamwork,
    this.scoreInitiative,
    this.scorePunctuality,
    this.scoreLeadership,
    this.scoreProblemSolving,
    this.scoreInnovation,
    this.strengths,
    this.areasForImprovement,
    this.goalsForNextPeriod,
    this.comments,
    this.performanceLevel,
    this.promotionRecommendation,
    this.promotionReadiness,
    this.trainingRecommendation,
    this.recognition,
    this.goalCompletionPercent,
    this.aiSummary,
    this.createdAt,
    this.selfAssessmentAt,
    this.selfAssessmentBy,
    this.managerReviewAt,
    this.managerReviewBy,
    this.hrApprovalAt,
    this.hrApprovalBy,
    this.finalApprovalAt,
    this.finalApprovalBy,
  });

  final int id;
  final String stage;
  final bool finalised;
  final int? employeeId;
  final String? employeeName;
  final String? reviewedByName;
  final String? reviewPeriodStart;
  final String? reviewPeriodEnd;
  final double? overallScore;

  final int? scoreWorkQuality;
  final int? scoreProductivity;
  final int? scoreCommunication;
  final int? scoreTeamwork;
  final int? scoreInitiative;
  final int? scorePunctuality;
  final int? scoreLeadership;
  final int? scoreProblemSolving;
  final int? scoreInnovation;

  final String? strengths;
  final String? areasForImprovement;
  final String? goalsForNextPeriod;
  final String? comments;
  final String? performanceLevel;
  final String? promotionRecommendation;
  final String? promotionReadiness;
  final String? trainingRecommendation;
  final String? recognition;
  final int? goalCompletionPercent;

  /// Generated by the AI module. Labelled as such wherever it is shown — a
  /// machine's summary of somebody's year should never be mistaken for their
  /// manager's words.
  final String? aiSummary;

  final String? createdAt;

  /// Who signed off which stage and when — stamped by `POST /{id}/advance`
  /// for the stage it just moved *past*, so [selfAssessmentAt] is only ever
  /// set once the review has left [PerformanceStage.selfAssessment], and so
  /// on. Absent entirely for a stage the review has not yet cleared.
  final String? selfAssessmentAt;
  final String? selfAssessmentBy;
  final String? managerReviewAt;
  final String? managerReviewBy;
  final String? hrApprovalAt;
  final String? hrApprovalBy;
  final String? finalApprovalAt;
  final String? finalApprovalBy;

  /// Every stage transition this review has actually recorded, oldest first
  /// — the audit trail the detail screen renders as a timeline. A stage with
  /// no timestamp yet (including the one currently in progress) is omitted
  /// rather than shown as a blank entry.
  List<({String stage, String? at, String? by})> get stageHistory => [
        (
          stage: PerformanceStage.selfAssessment,
          at: selfAssessmentAt,
          by: selfAssessmentBy,
        ),
        (
          stage: PerformanceStage.managerReview,
          at: managerReviewAt,
          by: managerReviewBy,
        ),
        (
          stage: PerformanceStage.hrApproval,
          at: hrApprovalAt,
          by: hrApprovalBy,
        ),
        (
          stage: PerformanceStage.finalApproval,
          at: finalApprovalAt,
          by: finalApprovalBy,
        ),
      ].where((s) => s.at != null).toList(growable: false);

  String get personLabel => employeeName?.trim().isNotEmpty == true
      ? employeeName!.trim()
      : 'Employee #${employeeId ?? id}';

  String get stageLabel =>
      PerformanceStage.labels[stage] ?? stage.replaceAll('_', ' ');

  int get stageIndex {
    final i = PerformanceStage.ordered.indexOf(stage);
    return i < 0 ? 0 : i;
  }

  bool get isComplete => stage == PerformanceStage.completed;

  /// A finalised review is a signed record. Nothing can move it on, and the
  /// screen must not offer to.
  bool get canAdvance => !finalised && !isComplete;

  /// Only a review that has reached the end can be signed off.
  bool get canFinalise => !finalised && isComplete;

  String? get period {
    final start = reviewPeriodStart;
    final end = reviewPeriodEnd;
    if (start == null && end == null) return null;
    return '${start ?? '?'} → ${end ?? '?'}';
  }

  /// The nine scored dimensions, in the order the form asks for them. Every
  /// one is optional, so the detail screen shows only those that were filled.
  List<ReviewScore> get scores => [
        ReviewScore('Work quality', scoreWorkQuality),
        ReviewScore('Productivity', scoreProductivity),
        ReviewScore('Communication', scoreCommunication),
        ReviewScore('Teamwork', scoreTeamwork),
        ReviewScore('Initiative', scoreInitiative),
        ReviewScore('Punctuality', scorePunctuality),
        ReviewScore('Leadership', scoreLeadership),
        ReviewScore('Problem solving', scoreProblemSolving),
        ReviewScore('Innovation', scoreInnovation),
      ];

  List<ReviewScore> get filledScores =>
      scores.where((s) => s.value != null).toList(growable: false);

  bool get hasScores => filledScores.isNotEmpty;

  /// The written half. Empty strings are treated as absent so a blank section
  /// never renders as a heading with nothing under it.
  List<({String title, String body})> get narrative {
    final sections = <({String title, String? body})>[
      (title: 'Strengths', body: strengths),
      (title: 'Areas to improve', body: areasForImprovement),
      (title: 'Goals for next period', body: goalsForNextPeriod),
      (title: 'Training suggested', body: trainingRecommendation),
      (title: 'Recognition', body: recognition),
      (title: 'Comments', body: comments),
    ];
    return [
      for (final s in sections)
        if (s.body?.trim().isNotEmpty == true)
          (title: s.title, body: s.body!.trim()),
    ];
  }

  factory PerformanceReview.fromJson(Map<String, dynamic> json) =>
      PerformanceReview(
        id: (json['id'] as num?)?.toInt() ?? 0,
        stage: json['stage'] as String? ?? PerformanceStage.selfAssessment,
        finalised: json['finalised'] as bool? ?? false,
        employeeId: (json['employeeId'] as num?)?.toInt(),
        employeeName: json['employeeName'] as String?,
        reviewedByName: json['reviewedByName'] as String?,
        reviewPeriodStart: json['reviewPeriodStart'] as String?,
        reviewPeriodEnd: json['reviewPeriodEnd'] as String?,
        overallScore: (json['overallScore'] as num?)?.toDouble(),
        scoreWorkQuality: (json['scoreWorkQuality'] as num?)?.toInt(),
        scoreProductivity: (json['scoreProductivity'] as num?)?.toInt(),
        scoreCommunication: (json['scoreCommunication'] as num?)?.toInt(),
        scoreTeamwork: (json['scoreTeamwork'] as num?)?.toInt(),
        scoreInitiative: (json['scoreInitiative'] as num?)?.toInt(),
        scorePunctuality: (json['scorePunctuality'] as num?)?.toInt(),
        scoreLeadership: (json['scoreLeadership'] as num?)?.toInt(),
        scoreProblemSolving: (json['scoreProblemSolving'] as num?)?.toInt(),
        scoreInnovation: (json['scoreInnovation'] as num?)?.toInt(),
        strengths: json['strengths'] as String?,
        areasForImprovement: json['areasForImprovement'] as String?,
        goalsForNextPeriod: json['goalsForNextPeriod'] as String?,
        comments: json['comments'] as String?,
        performanceLevel: json['performanceLevel'] as String?,
        promotionRecommendation: json['promotionRecommendation'] as String?,
        promotionReadiness: json['promotionReadiness'] as String?,
        trainingRecommendation: json['trainingRecommendation'] as String?,
        recognition: json['recognition'] as String?,
        goalCompletionPercent:
            (json['goalCompletionPercent'] as num?)?.toInt(),
        aiSummary: json['aiSummary'] as String?,
        createdAt: json['createdAt'] as String?,
        selfAssessmentAt: json['selfAssessmentAt'] as String?,
        selfAssessmentBy: json['selfAssessmentBy'] as String?,
        managerReviewAt: json['managerReviewAt'] as String?,
        managerReviewBy: json['managerReviewBy'] as String?,
        hrApprovalAt: json['hrApprovalAt'] as String?,
        hrApprovalBy: json['hrApprovalBy'] as String?,
        finalApprovalAt: json['finalApprovalAt'] as String?,
        finalApprovalBy: json['finalApprovalBy'] as String?,
      );
}

/// The nine competencies a review scores, in the order the form asks for them.
///
/// Each is 1–10 on the DTO. The annotations are never actually enforced —
/// neither the create nor the update endpoint carries `@Valid` — so the range
/// is the form's job, not the server's.
const reviewCompetencies = <({String key, String label})>[
  (key: 'scoreWorkQuality', label: 'Quality of work'),
  (key: 'scoreProductivity', label: 'Productivity'),
  (key: 'scoreCommunication', label: 'Communication'),
  (key: 'scoreTeamwork', label: 'Teamwork'),
  (key: 'scoreInitiative', label: 'Initiative'),
  (key: 'scorePunctuality', label: 'Punctuality'),
  (key: 'scoreLeadership', label: 'Leadership'),
  (key: 'scoreProblemSolving', label: 'Problem solving'),
  (key: 'scoreInnovation', label: 'Innovation'),
];

/// POST /hr/performance and PATCH /hr/performance/{id}
///
/// One class for both, because the backend uses one DTO for both.
///
/// The update path is a **true sparse patch** — every field is null-checked
/// before it is assigned, with no unguarded exceptions — so an omitted key
/// genuinely means "leave it alone". That is unusual in this codebase and
/// worth stating, because the neighbouring candidate and opportunity endpoints
/// behave the opposite way.
///
/// `employeeId` and the review period are only meaningful on create; the
/// update path ignores all three, so the edit form does not offer them.
///
/// `overallScore` is never sent: the service averages whichever competencies
/// are present, skipping nulls, and recomputes it on every write.
///
/// Deliberately absent: `goals`, which the DTO takes as a JSON array string
/// for the goal-tracking bars. Composing JSON by hand is not a phone task, and
/// omitting it leaves whatever the web app set.
class PerformanceReviewRequest {
  const PerformanceReviewRequest({
    this.employeeId,
    this.reviewPeriodStart,
    this.reviewPeriodEnd,
    this.scores = const {},
    this.strengths,
    this.areasForImprovement,
    this.goalsForNextPeriod,
    this.comments,
    this.performanceLevel,
    this.promotionRecommendation,
    this.trainingRecommendation,
    this.recognition,
    this.goalCompletionPercent,
  });

  final int? employeeId;
  final String? reviewPeriodStart;
  final String? reviewPeriodEnd;

  /// Keyed by the DTO's own field names — see [reviewCompetencies].
  final Map<String, int?> scores;

  final String? strengths;
  final String? areasForImprovement;
  final String? goalsForNextPeriod;
  final String? comments;
  final String? performanceLevel;
  final String? promotionRecommendation;
  final String? trainingRecommendation;
  final String? recognition;
  final int? goalCompletionPercent;

  factory PerformanceReviewRequest.from(PerformanceReview review) =>
      PerformanceReviewRequest(
        scores: {
          'scoreWorkQuality': review.scoreWorkQuality,
          'scoreProductivity': review.scoreProductivity,
          'scoreCommunication': review.scoreCommunication,
          'scoreTeamwork': review.scoreTeamwork,
          'scoreInitiative': review.scoreInitiative,
          'scorePunctuality': review.scorePunctuality,
          'scoreLeadership': review.scoreLeadership,
          'scoreProblemSolving': review.scoreProblemSolving,
          'scoreInnovation': review.scoreInnovation,
        },
        strengths: review.strengths,
        areasForImprovement: review.areasForImprovement,
        goalsForNextPeriod: review.goalsForNextPeriod,
        comments: review.comments,
        performanceLevel: review.performanceLevel,
        promotionRecommendation: review.promotionRecommendation,
        trainingRecommendation: review.trainingRecommendation,
        recognition: review.recognition,
        goalCompletionPercent: review.goalCompletionPercent,
      );

  Map<String, dynamic> toJson() {
    String? clean(String? value) {
      final trimmed = value?.trim();
      return (trimmed == null || trimmed.isEmpty) ? null : trimmed;
    }

    return {
      if (employeeId != null) 'employeeId': employeeId,
      if (reviewPeriodStart != null) 'reviewPeriodStart': reviewPeriodStart,
      if (reviewPeriodEnd != null) 'reviewPeriodEnd': reviewPeriodEnd,
      // An unscored competency is left out rather than sent as null, so on an
      // edit it keeps whatever it already had instead of being cleared.
      for (final entry in scores.entries)
        if (entry.value != null) entry.key: entry.value,
      if (clean(strengths) != null) 'strengths': clean(strengths),
      if (clean(areasForImprovement) != null)
        'areasForImprovement': clean(areasForImprovement),
      if (clean(goalsForNextPeriod) != null)
        'goalsForNextPeriod': clean(goalsForNextPeriod),
      if (clean(comments) != null) 'comments': clean(comments),
      if (clean(performanceLevel) != null)
        'performanceLevel': clean(performanceLevel),
      if (clean(promotionRecommendation) != null)
        'promotionRecommendation': clean(promotionRecommendation),
      if (clean(trainingRecommendation) != null)
        'trainingRecommendation': clean(trainingRecommendation),
      if (clean(recognition) != null) 'recognition': clean(recognition),
      if (goalCompletionPercent != null)
        'goalCompletionPercent': goalCompletionPercent,
    };
  }
}


// ─────────────────────────────────────────────────────────────
// Around the review: the objective figures for the period it
// covers, and the files kept with it.
// ─────────────────────────────────────────────────────────────

/// What the modules that own the data say about somebody over a period.
///
/// Nothing here is stored on the review. It is recomputed on every read from
/// attendance, leave, tasks, requests and client ratings, so the same period
/// reads the same way today as it did last week.
///
/// Several fields are deliberately nullable, and null does not mean zero: an
/// employee with no client ratings has an unknown satisfaction score, not a
/// score of nought. They are shown as a dash.
class PerformanceKpis {
  const PerformanceKpis({
    required this.daysPresent,
    required this.daysAbsent,
    required this.workingDaysRecorded,
    required this.lateArrivals,
    required this.leaveDaysTaken,
    required this.tasksCompleted,
    required this.projectsCompleted,
    this.employeeId,
    this.periodStart,
    this.periodEnd,
    this.attendancePercent,
    this.customerSatisfaction,
  });

  final int daysPresent;
  final int daysAbsent;

  /// Working days with an attendance record of any kind — the denominator.
  final int workingDaysRecorded;

  final int lateArrivals;
  final int leaveDaysTaken;
  final int tasksCompleted;
  final int projectsCompleted;
  final int? employeeId;
  final String? periodStart;
  final String? periodEnd;

  /// 0 to 100. Null when nothing was recorded for the period at all, which is
  /// different from an attendance of zero.
  final double? attendancePercent;

  /// The mean client rating, 1 to 5. Null when nobody rated their work.
  final double? customerSatisfaction;

  /// Whether there is anything worth showing. A period before the company
  /// started recording attendance comes back all zeroes and nulls.
  bool get hasAnything =>
      workingDaysRecorded > 0 ||
      tasksCompleted > 0 ||
      projectsCompleted > 0 ||
      leaveDaysTaken > 0;

  factory PerformanceKpis.fromJson(Map<String, dynamic> json) {
    int count(String key) => (json[key] as num?)?.toInt() ?? 0;

    return PerformanceKpis(
      daysPresent: count('daysPresent'),
      daysAbsent: count('daysAbsent'),
      workingDaysRecorded: count('workingDaysRecorded'),
      lateArrivals: count('lateArrivals'),
      leaveDaysTaken: count('leaveDaysTaken'),
      tasksCompleted: count('tasksCompleted'),
      projectsCompleted: count('projectsCompleted'),
      employeeId: (json['employeeId'] as num?)?.toInt(),
      periodStart: json['periodStart'] as String?,
      periodEnd: json['periodEnd'] as String?,
      attendancePercent: (json['attendancePercent'] as num?)?.toDouble(),
      customerSatisfaction: (json['customerSatisfaction'] as num?)?.toDouble(),
    );
  }
}

/// A file kept with a review.
class ReviewAttachment {
  const ReviewAttachment({
    required this.id,
    required this.fileName,
    required this.fileUrl,
    this.fileType,
    this.fileSizeBytes,
    this.label,
    this.uploadedByName,
    this.createdAt,
  });

  final int id;
  final String fileName;
  final String fileUrl;
  final String? fileType;
  final int? fileSizeBytes;
  final String? label;
  final String? uploadedByName;
  final String? createdAt;

  factory ReviewAttachment.fromJson(Map<String, dynamic> json) =>
      ReviewAttachment(
        id: (json['id'] as num?)?.toInt() ?? 0,
        fileName: json['fileName'] as String? ?? '',
        fileUrl: json['fileUrl'] as String? ?? '',
        fileType: json['fileType'] as String?,
        fileSizeBytes: (json['fileSizeBytes'] as num?)?.toInt(),
        label: json['label'] as String?,
        uploadedByName: json['uploadedByName'] as String?,
        createdAt: json['createdAt'] as String?,
      );
}

/// Recording a file against a review.
///
/// The file itself goes to `POST /upload` first; this only records what came
/// back. Nothing here carries bytes.
class ReviewAttachmentRequest {
  const ReviewAttachmentRequest({
    required this.fileName,
    required this.fileUrl,
    this.fileType,
    this.fileSizeBytes,
    this.label,
  });

  final String fileName;
  final String fileUrl;
  final String? fileType;
  final int? fileSizeBytes;
  final String? label;

  Map<String, dynamic> toJson() => {
        'fileName': fileName,
        'fileUrl': fileUrl,
        if (fileType != null) 'fileType': fileType,
        if (fileSizeBytes != null) 'fileSizeBytes': fileSizeBytes,
        if (label != null && label!.trim().isNotEmpty) 'label': label!.trim(),
      };
}
